### ISSUE TITLE
Project Architecture

### ISSUE THREAD

**Issue by shofi384** [FarhanHyder/PooledHouse#10]
Design/determine the project architecture

Project might be developed in two separate modules; 
- Fontend server using ReactJS and fetch api
- Backend server using node and express as RESTAPI
> For the database, we can utilize MongoDB which will be solely interacted with by the backend only. Frontend will make http requests to backend.

**Comment by FarhanHyder** [comment]
yeah, this seems correct. for now.

**Comment by FarhanHyder** [comment]
for the backend: let's look into the AWS.

**Comment by dgarsir** [comment]
think architecture is locked in. @FarhanHyder let's close this.
