### ISSUE TITLE
Prototyping

### ISSUE THREAD

**Issue by FarhanHyder** [FarhanHyder/PooledHouse#11]
Here are some examples to start with. Need feedback.

#### Homepage [as a visitor]
![Screenshot (35)](https://user-images.githubusercontent.com/17440230/54861533-e80cc300-4d00-11e9-84a0-d7022ad6771a.png)

#### Homepage [searching for a location]
![Screenshot (36)](https://user-images.githubusercontent.com/17440230/54861538-f3f88500-4d00-11e9-9e0b-78ae82ad727e.png)

**Comment by dgarsir** [comment]
This looks awesome Farhan, very close to what I was imagining.

**Comment by dgarsir** [comment]
![Screen Shot 2019-03-28 at 11 44 39 AM](https://user-images.githubusercontent.com/22826020/55171797-61684380-514f-11e9-8204-a25396048c78.png)
![Screen Shot 2019-03-28 at 11 44 59 AM](https://user-images.githubusercontent.com/22826020/55171801-63320700-514f-11e9-9445-ab61973e8ff8.png)
![Screen Shot 2019-03-28 at 11 45 17 AM](https://user-images.githubusercontent.com/22826020/55171803-64633400-514f-11e9-98f2-d47e83607a9c.png)
![Screen Shot 2019-03-28 at 11 44 05 AM](https://user-images.githubusercontent.com/22826020/55171814-6a591500-514f-11e9-9b13-0881f8671f5c.png)
