### ISSUE TITLE
the user pool is missing

### ISSUE THREAD

**Issue by shofi384** [FarhanHyder/PooledHouse#123]
Getting this error message while running 'snapshot' test on TipInfoForm.js: any idea where is this coming from? @dgarsir 
<img width="736" alt="Screen Shot 2019-05-05 at 10 22 10 PM" src="https://user-images.githubusercontent.com/21112959/57204225-4a094b00-6f84-11e9-9432-d532fc8517db.png">

**Comment by dgarsir** [comment]
@shofi384 it's possible that your aws config file is out of date--are you working off of the current master build? I had to remove all of our AWS services and reconfigure to get the database working again last week.

**Comment by shofi384** [comment]
Tried with the master build on local machine, still getting the error message.
It is not failing any tests, just giving the error message.

**Comment by dgarsir** [comment]
hmm.  If the test isn't failing, I wouldn't worry about it.  The user pool is certainly active on aws.  But let me know if anything else weird is happening.
