### ISSUE TITLE
AWS Technology Research

### ISSUE THREAD

**Issue by dgarsir** [FarhanHyder/PooledHouse#13]
What technologies should we use? Cognito for user info?

**Comment by FarhanHyder** [comment]
possible alternatives: 
- passport.js (http://www.passportjs.org/)

**Comment by dgarsir** [comment]
Amplify decided on, but running into issue brought up in class.

**Comment by dgarsir** [comment]
Will attempt to at least launch app from an s3 bucket, should be doable.

**Comment by dgarsir** [comment]
It works
