### ISSUE TITLE
Top Nav panel wireframe

### ISSUE THREAD

**Issue by ahamedbashir** [FarhanHyder/PooledHouse#133]
Top panel : three icon
1) Pooled house
2) circular toggle icon for map-list view
3) user icon

*user icon : on click or hovering- two menu
1) my tips
2) sign out
![top](https://user-images.githubusercontent.com/22090896/57394187-d9844900-7192-11e9-8849-1e8fa145423f.PNG)

**Comment by ahamedbashir** [comment]
For some reason, Image is rotated but on click it shows correctly

**Comment by FarhanHyder** [comment]
I think I implemented something similar. Got the idea from amazon.
![image](https://user-images.githubusercontent.com/17440230/57404258-8f5a9200-71a9-11e9-981f-8fc580396792.png)

But yeah, view my tips should be renamed to My Account or Your Account perhaps?
