### ISSUE TITLE
Web Body WireFrame

### ISSUE THREAD

**Issue by ahamedbashir** [FarhanHyder/PooledHouse#134]
1) Map view has Filter
2) List view has search button to search business
3) Select Business to see all information

![20190508_130426](https://user-images.githubusercontent.com/22090896/57394278-13554f80-7193-11e9-80d1-d501d52165ba.jpg)
![20190508_130401](https://user-images.githubusercontent.com/22090896/57394291-1f411180-7193-11e9-806a-46045ec2df24.jpg)

**Comment by dgarsir** [comment]
I'm alright with these changes, go for it.
