### ISSUE TITLE
Welcome Page Log in needs to be moved to the top panel

### ISSUE THREAD

**Issue by ahamedbashir** [FarhanHyder/PooledHouse#137]
Need a page before user log in. 
Log in button on the same location of the user Icon at the Top panel.
List view

**Comment by FarhanHyder** [comment]
wait?! what do you mean? I don't understand.

**Comment by ahamedbashir** [comment]
top panel will have a log in icon, clicking on that will open the log in or sign up page

**Comment by IanMFraser** [comment]
if i understand correctly, you're saying we need to find a way to default the page to opening on the home screen and not the amplify login page? is it possible to format the login page on aws to give a logo and brief description to what the user is logging on to?

**Comment by shofi384** [comment]
A page with "logo and brief description to what the user is logging on to" before the log-in will be great
