### ISSUE TITLE
Footer--can we remove it?  

### ISSUE THREAD

**Issue by dgarsir** [FarhanHyder/PooledHouse#140]
Looks a little tacky, and also for some reason the map clips through it.

Anyone disagree with removing it?

@FarhanHyder 
@IanMFraser 
@shofi384 
@ahamedbashir

**Comment by FarhanHyder** [comment]
Yeah. I have no objection. 
Removing it and making the Map full screen will produce a more "complete" look, I think.

**Comment by IanMFraser** [comment]
I agree. If it will help with the overall appearance, I have no objections.

**Comment by shofi384** [comment]
Sure, @dgarsir go ahead, if it makes the look better

**Comment by dgarsir** [comment]
Thanks guys, footer removed.
