### ISSUE TITLE
Tip Entry Fails

### ISSUE THREAD

**Issue by IanMFraser** [FarhanHyder/PooledHouse#157]
When inputting tip entries one after the other, the user gets a tip entry fails message.

**Comment by dgarsir** [comment]
Currently investigating.  Will update as necessary.  Not sure if frontend or backend issue yet.

**Comment by dgarsir** [comment]
Found the issue, looks like for some reason the the current user's username was being set to null after tipentry was created.  Testing the fix now.

**Comment by dgarsir** [comment]
Pushed fix.  Please close.

**Comment by dgarsir** [comment]
DOUBLY FIXED THERE WAS A PAGINATING ISSUE WITH APP SYNC IT'S ALL GOOD NOW BB

**Comment by IanMFraser** [comment]
Great! I'll close this issue.
