### ISSUE TITLE
Create Log In page 

### ISSUE THREAD

**Issue by IanMFraser** [FarhanHyder/PooledHouse#19]
When creating a login page there are two main fields that should be in consideration (plus one submit/login button):

* Username
* Password

How will we handle a situation where the user forget their username/password?  Should we have a link at the bottom that says something like "_Forgot Your Password?_" which would take the user a new page for password reset/retrieval?  

For front-end design, I will just add a link to mock this up, but we will need to address this issue further when we start to focus on back-end implementations.

**Comment by FarhanHyder** [comment]
completed by @IanMFraser 
but we will be using Amplify for this
