### ISSUE TITLE
Create function that converts an address input into the neighborhood

### ISSUE THREAD

**Issue by FarhanHyder** [FarhanHyder/PooledHouse#46]
```
func convertToNeighborhood(lat,lng)
{
       ........do some stuffs here.......
       returns neighborhoodID
}
```

**Comment by IanMFraser** [comment]
Is there a way to look up lat/long based on zipcode?

**Comment by FarhanHyder** [comment]
As of now, the problem is handled by just asking the user to enter their neighborhood. Although this is not intuitive, for now, it solves our problem.
