### ISSUE TITLE
#issue: react/merging

### ISSUE THREAD

**Issue by IanMFraser** [FarhanHyder/PooledHouse#6]
as we will be using react, we all need to install it in our local system first. So, how will we avoid the merging problems when we push our project to master? Do we just push part of the code? or do we need to push the whole project folder?

**Comment by FarhanHyder** [comment]
I tried the address-book hw problem (which I have in github) to clone into a different computer. Notably, I had to go through the process of doing `create-react-app address-book` and installing react-bootstrap process separately on the new machine. I have to say, the process is not easy. Not impossible to follow either. 
I'm still looking for easy options. Will keep you guys updated.

**Comment by dgarsir** [comment]
modules folder would be in gitignore, likely push all other files
