### ISSUE TITLE
Wireframing: What does this thing look like?

### ISSUE THREAD

**Issue by dgarsir** [FarhanHyder/PooledHouse#8]
Let's do some wireframes!

**Comment by FarhanHyder** [comment]
#### Here are some ideas to start with

### Homepage [as a visitor]
![Screenshot (35)](https://user-images.githubusercontent.com/17440230/54861468-9fa0d580-4cff-11e9-889e-661c6cdd78bc.png)

### Homepage [search for a location]
![Screenshot (36)](https://user-images.githubusercontent.com/17440230/54861475-cbbc5680-4cff-11e9-8829-7206e88043ab.png)

**Comment by dgarsir** [comment]
done.

**Comment by dgarsir** [comment]
![Screen Shot 2019-03-28 at 11 44 05 AM](https://user-images.githubusercontent.com/22826020/55178162-413e8180-515b-11e9-971c-728b84bc8424.png)
![Screen Shot 2019-03-28 at 11 44 39 AM](https://user-images.githubusercontent.com/22826020/55178168-44397200-515b-11e9-907d-3c9d3104ce7b.png)
![Screen Shot 2019-03-28 at 11 44 59 AM](https://user-images.githubusercontent.com/22826020/55178172-456a9f00-515b-11e9-99e6-c63612d52dd3.png)
![Screen Shot 2019-03-28 at 11 45 17 AM](https://user-images.githubusercontent.com/22826020/55178175-469bcc00-515b-11e9-8730-ce4aee7d7a7c.png)
