### ISSUE TITLE
My Tips-Kind of like a profile page?

### ISSUE THREAD

**Issue by dgarsir** [FarhanHyder/PooledHouse#82]
Feeling like MyTips should be styled as more of a profile page.  Anyone agree/disagree?

**Comment by IanMFraser** [comment]
I agree. 

I'm also thinking we should call that page differently than it currently is. Using onClick to toggle the TipUpdate form is maddening. 

I was thinking of trying to implement something like this...

https://medium.com/@krithix/multi-page-website-with-react-in-2017-f6f2af326526

**Comment by dgarsir** [comment]
Yeah, I explored the routing method a bit myself, but it seems like a bit overkill for what we're doing.  I think that we can get the functionality that we'd like just using conditional statements.  Just need to rewrite some of the app.js file.

**Comment by IanMFraser** [comment]
Maybe overkill, but maybe not? I feel like it could organize our workflow and tidy our App.js. We'll discuss at our next meeting.

**Comment by FarhanHyder** [comment]
we did not implement it with a "multi-page" design, but MyTips has been updated with a more profile-like page.
