### ISSUE TITLE
User Feedback Poll

### ISSUE THREAD

**Issue by dgarsir** [FarhanHyder/PooledHouse#9]
Thinking about creating a SurveyMonkey poll to get some ideas from coworkers.  Thoughts on questions to include?

**Comment by FarhanHyder** [comment]
- what kind of functionalities will motivate you as a user to input your income details into PH?
        - nice user interface?
        - anonymity?
        - or are you just happy to contribute to help the community grow?

- if you already have a job, and not looking to switch your job in the near future, what kind you functionalities do you think will motivate you to keep coming back to the website at least once a week?

**Comment by dgarsir** [comment]
Poll created, awaiting responses.

https://forms.gle/PvTjv7pZpDLZ3dZZA
