### ISSUE TITLE
Wireframing for MyTips page

### ISSUE THREAD

**Issue by FarhanHyder** [FarhanHyder/PooledHouse#94]
## option 1
![image](https://user-images.githubusercontent.com/17440230/57002138-38dacb80-6b8b-11e9-99a0-dcc8e4e0b9b8.png)

## option 2
![image](https://user-images.githubusercontent.com/17440230/57002145-47c17e00-6b8b-11e9-9ba7-911ef5a5ac30.png)

which one looks better?
or if you have any other preference please submit your version.

**Comment by ahamedbashir** [comment]
good. will complete this soon

**Comment by dgarsir** [comment]
Option 2 looks good.  @ahamedbashir I think @FarhanHyder is taking this bit.

**Comment by IanMFraser** [comment]
Option 2 is nice.

**Comment by FarhanHyder** [comment]
option 2 is selected for implementation.
